package faker.specs.address


import spock.lang.Specification
import spock.lang.Unroll;
import faker.Address

class GeographicCoordinatesTest extends Specification {

    def "latitude #lat"(def lat) {
        expect: "the output should be between -90 and +90"
        assert lat >= -90
        assert lat <= 90

        where: "latitude is generated by Address.latitude()"
        lat << (1..1000).collect { Address.latitude() }
    }

    def "longitude #l"(def l){
        expect: "the output should be between -180 and +180"
        assert l >= -180
        assert l <= 180

        where: "I call Address.longitude()"
        l << (1..1000).collect { Address.longitude() }
    }
}