package faker.specs.stringsimport spock.lang.Specificationimport faker.Strings
class Alphabetic extends Specification {

    def "alphabetic with fixed length"(def string) {
        expect: "the generated string is an alphabetic string"        assert string ==~ /[a-zA-Z]+/        and: "the generated string has length 5"        assert string.size() == 5
        where: "the string is generated by Strings.alphabetic(5)"
        string << (1..1000).collect { Strings.alphabetic(5) }    }
    def"alphabetic with range length"(def string) {
        expect: "the generated string is an alphabetic string"
        assert string ==~ /[a-zA-Z]+/        and: "the generated string has length 4..8"
        assert string.size() in 4..8
        where: "the string is generated by Strings.alphabetic(4..8)"
        string << (1..1000).collect { Strings.alphabetic(4..8) }    }}