package faker.specs.strings

import spock.lang.Specification
import faker.Strings

class NumericTest extends Specification {

    def "numeric with fixed length"(def number) {
        expect: "the generated number is a valid number"
        Integer.parseInt(number)

        and: "the generated number has length 5"
        assert number.size() == 5

        where: "the string is generated by Strings.numeric(5)"
        number << (1..1000).collect { Strings.numeric(5) }
    }

    def "numeric with range length"(def number) {
        expect: "the generated number is a valid number"
        Integer.parseInt(number)

        and: "the generated number has length 4..8"
        assert number.size() in 4..8

        where: "the string is generated by Strings.numeric(4..8)"
        number << (1..1000).collect { Strings.numeric(4..8) }
    }
}