package faker.specs.strings

import spock.lang.Specification
import faker.Strings

class XegerTest extends Specification {

    static regex
    
    def setupSpec() {
        regex = /^[A-PR-UWYZ0-9][A-HK-Y0-9][AEHMNPRTVXY0-9]?[ABEHMNPRVWXY0-9]? {1,2}[0-9][ABD-HJLN-UW-Z]{2}$/
    }
    
    def "regular expression"(def s) {
        expect: "the generated string matches the regular expression"
        assert s ==~ regex

        where: "the string is generated by Strings.xeger(regex)"
        s << (1..1000).collect { Strings.xeger(regex) }
    }
}