package faker.specs.lorem

import spock.lang.Specification
import faker.Lorem
import faker.specs.support.Localized

@Localized
class QuantityMultipleParagraphsTest extends Specification {

    def "paragraphs, no number of paragraphs"(def paragraphs) {
        expect: "the resulting list should be 3 paragraphs"
        assert paragraphs.size() == 3

        where: "the paragraphs are generated by Lorem.paragraphs()"
        paragraphs << (1..100).collect { Lorem.paragraphs() }
    }

    def "paragraphs, exact number of paragraphs"(def paragraphs) {
        expect: "the resulting list should be 5 paragraphs"
        assert paragraphs.size() == 5

        where: "the paragraphs are generated by Lorem.paragraphs(5)"
        paragraphs << (1..100).collect { Lorem.paragraphs(5) }
    }

    def "paragraphs, range number of paragraphs"(def paragraphs) {
        expect: "the resulting list should be 3..6 paragraphs"
        assert paragraphs.size() in 3..6

        where: "the paragraphs are generated by Lorem.paragraphs(3..6)"
        paragraphs << (1..100).collect { Lorem.paragraphs(3..6) }
    }

    def "paragraphs, list number of paragraphs"(def paragraphs) {
        expect: "the resulting list should be 1 or 4 paragraphs"
        assert paragraphs.size() in [1, 4]

        where: "the paragraphs are generated by Lorem.paragraphs([1, 4])"
        paragraphs << (1..100).collect { Lorem.paragraphs([1, 4]) }
    }
}

